### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by wudongming97** [ZCMax/ScanReason#1]
Hi @ZCMax ,

This is a great work! Could you let me know when you'll release the code?

**Comment by ZCMax** [comment]
Thank you very much for your attention! We'll release the data and code in the next two weeks~

**Comment by aabdelreheem55** [comment]
Hi @ZCMax , I hope you're doing well! I was wondering if you have any estimate on when the code might be released. No rush at all—just curious. Thanks!

**Comment by ZCMax** [comment]
Thanks for your interest in our work, due to the heavy 3D feature process
in the original 3D-LLM method, we are currently building a much stronger,
user-friendly, and faster multimodal 3D LLM (3D Foundation Model) to
replace the original 3D-LLM in the paper, and our currently developed 3D
LLM is expected to be released at the end of August or the beginning of
September, and the ReGround3D code will be released together with this new
3D LLM (3D foundation model).

aabdelreheem55 ***@***.***> 于2024年8月21日周三 00:56写道：

**Comment by ZCMax** [comment]
The codes has been released, data stays tuned~

**Comment by Samir55** [comment]
@ZCMax,  I was wondering if you could provide guidance on where to find the checkpoint for the point encoder named butd_detr_scanrefer_backbone.pth. It would be greatly appreciated.
